services:
  frontend:
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./public:/app/public
      - ./src:/app/src
    build:
      context: .
      dockerfile: Dockerfile.reactUI
    ports:
      - "3000:3000"    
    depends_on:
      - db
  nodebackend: 
    volumes:
      - ./server:/app
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./server
      dockerfile: Dockerfile.node
    ports: 
      - "9000:9000"    #external:internal 
    depends_on:
      - db
  db:
    volumes:
      - uasa_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  
volumes:
   uasa_db:
